<?php
declare(strict_types=1);

if (!getenv('WALLET_WP_PATH')) { throw new RuntimeException('Set an isolated WALLET_WP_PATH.'); }
require rtrim(getenv('WALLET_WP_PATH'), '/') . '/wp-load.php';
require __DIR__ . '/bootstrap.php';
require __DIR__ . '/split-cases.php';
add_filter('pre_wp_mail', static fn () => true);

use WalletPlatform\Application\SplitPaymentService;
use WalletPlatform\Bootstrap\Plugin;
use WalletPlatform\Domain\Shared\Currency;
use WalletPlatform\Domain\Shared\Money;
use WalletPlatform\WooCommerce\Orders\PayPalOrders;
use WalletPlatform\WooCommerce\Gateway\PayPalGateway;
use WalletPlatform\WordPress\Rest\PayPalController;

update_option('woocommerce_currency', 'USD');
$uid = wp_create_user('wallet_split_' . bin2hex(random_bytes(5)), wp_generate_password(32), 'split_' . bin2hex(random_bytes(5)) . '@example.invalid');
if (is_wp_error($uid)) { throw new RuntimeException($uid->get_error_message()); }
wp_set_current_user($uid);
$services = Plugin::services();
$currency = Currency::of('USD');
$account = $services->wallets->account($uid, $currency)['id'];
$services->wallets->credit($account, new Money(1000, $currency), 'split:seed:' . $uid, 0, 'Split integration fixture');
$provider = new SagaProviderFixture(true);
$saga = new SplitPaymentService($services->wallets, $services->holds, $services->refunds, $provider);
$orders = new PayPalOrders($services, $saga);
$orders->register();
$gateway = new PayPalGateway($services, $orders, true);
add_filter('woocommerce_payment_gateways', static function (array $gateways) use ($gateway): array { $gateways[] = $gateway; return $gateways; });
WC()->payment_gateways()->init();
$product = new WC_Product_Simple();
$product->set_name('Split fixture product');
$product->set_regular_price('30.00');
$product->set_virtual(true);
$product->save();
$order = wc_create_order(['customer_id' => $uid]);
$order->add_product($product, 1);
$order->set_payment_method('wallet_platform_paypal');
$order->calculate_totals();
$_POST['wallet_paypal_amount'] = '10.00';
$_POST['wallet_paypal_gross'] = '30.00';
rejects('payment_quote_changed', fn () => $orders->start($order, new Money(1000, $currency), new Money(3100, $currency)));
rejects('payment_quote_changed', fn () => $orders->start($order, new Money(1100, $currency), new Money(3000, $currency)));
same(0, $provider->creates);
same('success', $gateway->process_payment($order->get_id())['result']);
$payment = $orders->forOrder($order->get_id());
same('0.00', $services->queries->balance($account)['available']);
same('10.00', $services->queries->balance($account)['reserved']);
same(false, wc_get_order($order->get_id())->is_paid());
same('success', $gateway->process_payment($order->get_id())['result']);
same(1, $provider->creates);
$controller = new PayPalController($orders);
parse_str(parse_url($orders->callbackUrl($payment, $order, false), PHP_URL_QUERY), $return);
$return['token'] = $provider->orderId;
same($payment['id'], $controller->authorizeReturn($return)['id']);
rejects('payment_owner_mismatch', fn () => $controller->authorizeReturn(array_replace($return, ['wallet_nonce' => 'wrong'])));
rejects('payment_owner_mismatch', fn () => $controller->authorizeReturn(array_replace($return, ['token' => 'OTHER00000000001'])));
wp_set_current_user($uid + 1000000);
rejects('payment_owner_mismatch', fn () => $controller->authorizeReturn($return));
wp_set_current_user($uid);
$order = wc_get_order($order->get_id());
$order->set_payment_method('wallet_platform');
$order->save();
same('failure', WC()->payment_gateways()->payment_gateways()['wallet_platform']->process_payment($order->get_id())['result']);
same('10.00', $services->queries->balance($account)['reserved']);
$order->set_payment_method('wallet_platform_paypal');
$order->save();
$provider->approve();
same('completed', $orders->recover($payment['id'])['state']);
same(true, wc_get_order($order->get_id())->is_paid());
same('30.00', wc_get_order($order->get_id())->get_total());
same('completed', $orders->cancelByOwner($payment['id'], $uid)['state']);
same(true, wc_get_order($order->get_id())->is_paid());
same(0, $provider->refundCalls);
same('success', $gateway->process_payment($order->get_id())['result']);
same(1, $provider->captures);
echo "PASS fixture-provider split order, immutable gross, nonce/owner/token checks, retry and stale cancel protection\n";

$admin = get_user_by('login', 'wallet_test_admin');
if (!$admin) { throw new RuntimeException('Isolated wallet_test_admin is missing.'); }
wp_set_current_user($admin->ID);
$provider->refundStatus = 'PENDING';
$pending = wc_create_refund(['order_id' => $order->get_id(), 'amount' => '10.00', 'reason' => 'Pending split fixture refund', 'refund_payment' => true]);
same(true, is_wp_error($pending));
same(0, count(wc_get_order($order->get_id())->get_refunds()));
$intent = $services->db->row('SELECT * FROM ' . $services->db->table('payment_refunds') . ' WHERE payment_id=?', [$payment['id']]);
same('pending', $intent['state']);
same('0.00', $services->queries->balance($account)['available']);
$duplicate = wc_create_refund(['order_id' => $order->get_id(), 'amount' => '10.00', 'reason' => 'Accidental repeated pending request', 'refund_payment' => true]);
same(true, is_wp_error($duplicate));
same(1, $provider->refundCalls);
$provider->refundStatus = 'COMPLETED';
$orders->recoverRefund($intent['id']);
$orders->recoverRefund($intent['id']);
same(1, count(wc_get_order($order->get_id())->get_refunds()));
same('3.33', $services->queries->balance($account)['available']);
same(1, $provider->refundCalls);
$final = wc_create_refund(['order_id' => $order->get_id(), 'amount' => '20.00', 'reason' => 'Remaining split fixture refund', 'refund_payment' => true]);
same(false, is_wp_error($final));
same('10.00', $services->queries->balance($account)['available']);
same('refunded', wc_get_order($order->get_id())->get_status());
same(2, $provider->refundCalls);
same(true, $services->reconciliation->account($account)['healthy']);
echo "PASS pending external refund restores deleted WooCommerce refund CRUD once and conserves cumulative cents\n";

wp_set_current_user($uid);
$_SERVER['HTTPS'] = 'on'; // Isolated in-process Store API contract; no provider network or TLS claim.
$_SERVER['HTTP_HOST'] = '127.0.0.1:13317';
wc_clear_notices();
wc_load_cart();
WC()->customer = new WC_Customer($uid, true);
$provider->orderId = 'ORDER' . strtoupper(bin2hex(random_bytes(8)));
$provider->captureId = 'CAPTURE' . strtoupper(bin2hex(random_bytes(8)));
WC()->cart->add_to_cart($product->get_id(), 1);
WC()->cart->calculate_totals();
$request = new WP_REST_Request('POST', '/wc/store/v1/checkout');
$request->set_header('Nonce', wp_create_nonce('wc_store_api'));
$request->set_body_params(['payment_method' => 'wallet_platform_paypal', 'billing_address' => ['first_name' => 'Split', 'last_name' => 'Fixture', 'address_1' => '1 Test Street', 'city' => 'Los Angeles', 'state' => 'CA', 'postcode' => '90210', 'country' => 'US', 'email' => 'split_' . $uid . '@example.invalid', 'phone' => '5551234567'], 'payment_data' => [['key' => 'wallet_paypal_amount', 'value' => '10.00'], ['key' => 'wallet_paypal_gross', 'value' => '30.00']]]);
$response = rest_get_server()->dispatch($request);
if ($response->get_status() !== 200) { throw new RuntimeException('Split Store API failed: ' . wp_json_encode($response->get_data())); }
$data = $response->get_data();
same('success', $data['payment_result']['payment_status']);
same(false, wc_get_order($data['order_id'])->is_paid());
same('10.00', $services->queries->balance($account)['reserved']);
$blockPayment = $orders->forOrder($data['order_id']);
$provider->approve();
same('completed', $orders->recover($blockPayment['id'])['state']);
same(true, wc_get_order($data['order_id'])->is_paid());
same('0.00', $services->queries->balance($account)['available']);
same(true, $services->reconciliation->account($account)['healthy']);
$method = new \WalletPlatform\WooCommerce\Blocks\PayPalMethod(dirname(__DIR__) . '/woocommerce-wallet.php', true);
$method->initialize();
same(true, $method->is_active());
same(['wallet-platform-paypal-blocks'], $method->get_payment_method_script_handles());
same(true, wp_script_is('wc-blocks-data-store', 'registered'));
$webhook = new WP_REST_Request('POST', '/wallet-platform/v1/paypal/webhook');
$webhook->set_body('{"id":"WH-FORGED"}');
same(400, $controller->webhook($webhook)->get_status());
echo "PASS real Store API split redirect/reservation/settlement with fixture provider and registered Blocks dependencies\n";

wp_set_current_user($admin->ID);
$crashOrder = wc_get_order($data['order_id']);
$intent = $saga->prepareRefundIntent($blockPayment['id'], new Money(3000, $currency), 'wc:crash-refund:' . $crashOrder->get_id(), ['order_id' => $crashOrder->get_id(), 'original_refund_id' => 0, 'actor_id' => $admin->ID, 'reason' => 'First-save interruption fixture', 'line_items' => []]);
same('completed', $saga->recoverRefund($intent['id'])['state']);
$firstSave = new WC_Order_Refund();
$firstSave->set_parent_id($crashOrder->get_id());
$firstSave->set_currency('USD');
$firstSave->set_amount('30.00');
$firstSave->set_total('-30.00');
$firstSave->update_meta_data('_wallet_payment_refund_id', $intent['id']);
$firstSave->save(); // Persist only the first-save state, without the normal parent-status pipeline.
same(true, wc_get_order($crashOrder->get_id())->is_paid());
$calls = $provider->refundCalls;
$orders->recoverRefund($intent['id']);
$orders->recoverRefund($intent['id']);
same('refunded', wc_get_order($crashOrder->get_id())->get_status());
same(1, count(wc_get_order($crashOrder->get_id())->get_refunds()));
same($calls, $provider->refundCalls);
same('10.00', $services->queries->balance($account)['available']);

$provider->orderId = 'ORDER' . strtoupper(bin2hex(random_bytes(8)));
$provider->captureId = 'CAPTURE' . strtoupper(bin2hex(random_bytes(8)));
$foreign = wc_create_order(['customer_id' => $uid]);
$foreign->add_product($product, 1);
$foreign->set_payment_method('wallet_platform_paypal');
$foreign->calculate_totals();
wp_set_current_user($uid);
$foreignPayment = $orders->start($foreign, new Money(1000, $currency), new Money(3000, $currency));
$provider->approve();
$orders->recover($foreignPayment['id']);
$foreign = wc_get_order($foreign->get_id());
$foreign->set_transaction_id('another-payment-reference');
$foreign->save();
same('compensated', $orders->recover($foreignPayment['id'])['state']);
$compensation = $services->db->row('SELECT id FROM ' . $services->db->table('payment_refunds') . ' WHERE payment_id=?', [$foreignPayment['id']]);
rejects('refund_conflict', fn () => $orders->recoverRefund($compensation['id']));
same(0, count(wc_get_order($foreign->get_id())->get_refunds()));
same('another-payment-reference', wc_get_order($foreign->get_id())->get_transaction_id());
same(true, $services->reconciliation->account($account)['healthy']);
echo "PASS first-save refund interruption repairs parent status once and foreign payment references block sales-refund recovery\n";
echo "No real PayPal API, sandbox approval, webhook or settlement was exercised.\n";
